#!/usr/bin/env bash

monitor_count=$(hyprctl monitors | awk '/Monitor/ { print $0 }' | wc -l)
if [ "$monitor_count" == "2" ]; then
	hyprctl keyword monitor HDMI-A-1,enable
	hyprctl keyword monitor eDP-1,disable
fi
